name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_SHORT_INFO: true
          SHOW_PROFILE_VIEWS: false
          SHOW_TIMEZONE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_PROJECTS: false
          SHOW_OS: true
          SHOW_EDITORS: true
          SYMBOL_VERSION: 2
          SHOW_LOC_CHART: true
          SHOW_UPDATED_DATE: true
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
