name: Waka Readme

on:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_TIMEZONE: "True"
          SHOW_LOC_CHART: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
